version: '3'
services:
  front:
    build:
      context: .
      dockerfile: Dockerfile_nextjs
    volumes:
      - .:/usr/src
    ports:
      - 3000:3000
    command: sh -c "cd photo-to-icon && npm run dev"
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
  back:
    build:
      context: .
      dockerfile: Dockerfile_python
    volumes:
      - ./python:/var/www/html
    ports:
      - 9004:9004
    command: uvicorn main:app --reload --host 0.0.0.0 --port 9004
    tty: true


